services:
  ff-proxy:
    image: gofeatureflag/go-feature-flag:v1.49
    volumes:
      - ./ff-proxy/goff-proxy.yaml:/goff/goff-proxy.yaml
      - ./ff-proxy/flags:/flags
    ports:
      - "1031:1031"
    networks:
      - main
networks:
  main:
