services:
  ff-proxy:
    image: gofeatureflag/go-feature-flag:v1.49
    volumes:
      - ./ff-proxy/goff-proxy.yaml:/goff/goff-proxy.yaml
    ports:
      - "1031:1031"
    networks:
      - main
  ff-storage:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    volumes:
      - ./ff-storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
networks:
  main:
